on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Yak Build & Publish
    steps:
      - uses: actions/checkout@v3

      - id: yak
        uses: crashcloud/yak@v1
        with:
          package-name: MyPackage
          token: ${{ secrets.YAK_TOKEN }}
          build-path: src/project/bin/**/x64/
          test-run: true
          platforms:
            - win
      - run: Echo Random Number
        shell: |
          echo random-number ${{ steps.yak.outputs.result }}
